---

version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.3

workflows:
  shellcheck:
    jobs:
      - shellcheck/check
      - rubocop

jobs:
  rubocop:
    docker:
      - image: mckern/ruby:latest
    steps:
      - checkout
      - run:
          name: Run RuboCop linting
          command: |
            rubocop \
              --parallel \
              --display-cop-names \
              --display-style-guide \
              --require rubocop/formatter/junit_formatter \
              --format progress \
              --out /tmp/test-results/rubocop.xml \
              --format RuboCop::Formatter::JUnitFormatter
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
