---

version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.3

workflows:
  shellcheck:
    jobs:
      - shellcheck/check
      - rubocop

jobs:
  rubocop:
    docker:
      - image: mckern/ruby:latest
    steps:
      - checkout
      - run:
          name: Run RuboCop linting
          command: |
            rubocop --parallel --display-cop-names --display-style-guide
